#!/usr/bin/env python3
"""Generate the wide-codepoint table from checked-in Unicode 17 data.

Run with --check in CI. No network access or third-party modules are needed.
"""

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "tools/unicode/EastAsianWidth-17.0.0.txt"
DESTINATION = ROOT / "src/unicode_widths.zig"
SOURCE_SHA256 = "ea7ce50f3444a050333448dffef1cadd9325af55cbb764b4a2280faf52170a33"


def generate():
    data = SOURCE.read_bytes()
    if hashlib.sha256(data).hexdigest() != SOURCE_SHA256:
        raise SystemExit("Unicode input checksum mismatch; review the source before updating it")
    ranges = []
    for line in data.decode("utf-8").splitlines():
        fields = line.partition("#")[0].strip()
        if not fields:
            continue
        span, width = (field.strip() for field in fields.split(";"))
        if width not in ("W", "F"):
            continue
        ends = span.split("..")
        lo, hi = int(ends[0], 16), int(ends[-1], 16)
        if ranges and lo == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], hi)
        else:
            ranges.append((lo, hi))
    lines = [
        "// Generated by tools/generate_widths.py. Do not edit.",
        "// Unicode 17.0.0 EastAsianWidth W/F; see tools/unicode/LICENSE.txt.",
        "pub const Range = struct { lo: u21, hi: u21 };",
        "",
        "pub const double_width = [_]Range{",
    ]
    lines.extend(f"    .{{ .lo = 0x{lo:04x}, .hi = 0x{hi:04x} }}," for lo, hi in ranges)
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate()
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text() != result:
            raise SystemExit("Width table is stale; run python3 tools/generate_widths.py")
        print("Unicode width table matches the pinned source.")
    else:
        DESTINATION.write_text(result)


if __name__ == "__main__":
    main()
